name: Deploy via FTP

on:
  push:
    branches:
      - main  # Se a sua branch principal for "master", altere aqui

jobs:
  web-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Pegando o código mais recente
      uses: actions/checkout@v4

    - name: 🚀 Sincronizando arquivos via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # No InfinityFree, o site deve ir para dentro de htdocs
        server-dir: htdocs/
        # Garante que arquivos deletados localmente também sejam apagados no servidor
        delete-clean: true