name: Deploy via FTP

on:
  push:
    branches:
      - main  # Verifique se a sua branch principal é main ou master

jobs:
  web-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Pegando o código mais recente
      uses: actions/checkout@v4

    - name: 🚀 Sincronizando arquivos via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/
        # Correção do parâmetro de limpeza (opcional, remova a linha se preferir não deletar nada)
        dangerous-clean-slate: false